const columns = [
  { name: "#", uid: "id" },
  { name: "NAME", uid: "name" },
  { name: "TITLE", uid: "title" },
  { name: "TYPE", uid: "type" },
  { name: "CREATED AT", uid: "created_at" },
  { name: "ACTIONS", uid: "actions" },
];

const ticketsData: TicketDataTypes[] = [
  {
    id: 1,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Feb 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 3,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Student",
    created_at: "Mar 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 4,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 5,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 6,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Teacher",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 7,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 8,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 9,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 10,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 11,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 12,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 13,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 14,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 15,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 16,
    name: "Hasanul Hoque Banna",
    title: "How it works?",
    type:"Organization",
    created_at: "Jan 2, 2020",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
];

export { columns, ticketsData };
